### ISSUE TITLE
неверное условие в скобках

### ISSUE THREAD

**Issue by asraysun** [denis-lyubimov/javaRushCaesarCode#1]
if (key > 1 && key < 42) {
                    System.out.printf("ключ может иметь значение от 1го до 42х, Вы ввели %d", key);
                    continue;
                } 
исправь знаки

https://github.com/denis-lyubimov/javaRushCaesarCode/blob/e8156ff2c666a9ca879a0b8c41adbe3a0864d35d/src/CoderEncoder.java#L78

**Comment by denis-lyubimov** [comment]
поправил на 
https://github.com/denis-lyubimov/javaRushCaesarCode/blob/467a6fa5edc99557356e6e207387fc1f7574d141/src/CoderEncoder.java#L77
